Repository Idealiste-cz/ideal-voting-backend, pull requests merged in 2022-05, with the labels that each got.

#308 Update sbt-guardrail to 0.70.0.2
  project/plugins.sbt
Labels: type: dependencies

#311 Update sbt-decent-scala to 0.8.0
  project/plugins.sbt
Labels: type: dependencies, type: breaking

#313 zio-doobie 0.3.0
  ideal-voting-server/src/main/resources/reference.conf
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/Config.scala
  ideal-voting-server/src/test/scala/cz/idealiste/idealvoting/server/TestContainer.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: mergify-merge

#314 Update sbt-decent-scala to 0.8.0+2-ed216716
  project/plugins.sbt
Labels: type: dependencies

#315 Update scalafmt-core to 3.5.3
  .scalafmt.conf
Labels: type: dependencies

#317 Update sbt-decent-scala to 0.8.0+3-59414f5f
  project/plugins.sbt
Labels: type: dependencies

#319 Remove upcastLayer, use just .toLayer[Xyz]
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/DbDoobie.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/VotingLive.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/VotingSystemDummy.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/package.scala
Labels: mergify-merge

#316 Update jackson-databind to 2.13.3
  project/Dependencies.scala
Labels: type: dependencies

#320 Dissolve Http classes into multiple
  build.sbt
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/Config.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/Handler.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/HandlerLive.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/Http.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/HttpApp.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/HttpAppLive.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/HttpServer.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/HttpServerBlaze.scala
  ideal-voting-server/src/main/scala/cz/idealiste/idealvoting/server/Main.scala
  ideal-voting-server/src/test/scala/cz/idealiste/idealvoting/server/MainSpec.scala
  project/Dependencies.scala
Labels: mergify-merge

#321 Update circe-generic, circe-parser to 0.14.2
  project/Dependencies.scala
Labels: type: dependencies

#322 Compatibility.BinaryCompatible
  build.sbt
Labels: mergify-merge

#324 Update http4s-blaze-server, http4s-circe, ... to 0.23.12
  project/Dependencies.scala
Labels: type: dependencies
