Repository Idealiste-cz/ideal-voting-backend, pull requests merged in 2022-08, with the labels that each got.

#347 Update sbt-decent-scala to 0.8.0+12-c655e6fe
  project/plugins.sbt
Labels: type: dependencies

#350 Update sbt-decent-scala to 0.8.0+13-dca3db3b
  project/plugins.sbt
Labels: type: dependencies

#352 Use sbt-dependency-submission
  .github/workflows/dependency-graph.yml
Labels: mergify-merge

#354 Use setup-java
  .github/workflows/ci.yml
Labels: mergify-merge

#355 Update sbt-guardrail
  project/plugins.sbt
Labels: mergify-merge

#353 Update http4s, but keep blaze
  build.sbt
  project/Dependencies.scala
Labels: mergify-merge

#348 Update mariadb-java-client to 3.0.7
  project/Dependencies.scala
Labels: type: dependencies, type: breaking

#359 Update sbt-decent-scala to 0.9.0+2-59ef6310
  project/plugins.sbt
Labels: type: dependencies

#360 Update zio-testcontainers to 0.4.1
  project/Dependencies.scala
Labels: type: dependencies

#361 Stylistic changes in TestContainer
  ideal-voting-server/src/test/scala/cz/idealiste/idealvoting/server/TestContainer.scala
Labels: mergify-merge

#362 Update zio-test, zio-test-sbt to 2.0.1
  project/Dependencies.scala
Labels: type: dependencies

#364 Update sbt-decent-scala to 0.9.0+3-a7ca7d7f
  project/plugins.sbt
Labels: type: dependencies

#366 sbt-guardrail 0.75.0
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: mergify-merge

#367 Set logging to WARN for org.mariadb and docker-compose
  ideal-voting-server/src/main/resources/logback.xml
  ideal-voting-server/src/test/resources/logback-test.xml
Labels: mergify-merge

#370 Update http4s-circe, http4s-client, ... to 0.23.15
  project/Dependencies.scala
Labels: type: dependencies

#373 Update zio-test, zio-test-sbt to 2.0.2
  project/Dependencies.scala
Labels: type: dependencies
